domain_path: D:\DAS_200_ps\DAS_200_platform\export\DAS_200_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\lwip_udp_perf_server
template: lwip_udp_perf_server
lang: c
